import React, { useState, useEffect } from 'react';
import { Card, Form, Input, Button, Select, DatePicker, message, Row, Col, Divider, Modal, Descriptions, Tag } from 'antd';
import { UserOutlined, CheckCircleOutlined } from '@ant-design/icons';
import axios from 'axios';
import dayjs from 'dayjs';
import { useLOVValues } from '../../../hooks/useLOVValues';

const { Option } = Select;

const EmployeeRegistration = () => {
  const [form] = Form.useForm();
  const [loading, setLoading] = useState(false);
  const [successModalVisible, setSuccessModalVisible] = useState(false);
  const [createdEmployee, setCreatedEmployee] = useState(null);

  // ✅ Fetch dropdown values from LOV system (Form ID: 4 - EmployeeRegistration)
  // Note: Designator names must be lowercase to match backend API
  const { lovValues: departmentLOV, loading: loadingDepartments } = useLOVValues(4, 'department');
  const { lovValues: designationLOV, loading: loadingDesignations } = useLOVValues(4, 'designation');
  const { lovValues: locationLOV, loading: loadingLocations } = useLOVValues(4, 'location');

  const handleSubmit = async (values) => {
    try {
      setLoading(true);

      const payload = {
        // ❌ DO NOT send employeeId - it's auto-generated by backend
        firstName: values.firstName,
        lastName: values.lastName,
        emailAddress: values.emailAddress,
        phoneNumber: values.phoneNumber,
        dateOfBirth: values.dateOfBirth ? values.dateOfBirth.format('YYYY-MM-DD') : null,
        jobTitle: values.jobTitle,
        designation: values.designation,
        departmentName: values.departmentName,
        manager: values.manager,
        employmentType: values.employmentType,
        hireDate: values.hireDate ? values.hireDate.format('YYYY-MM-DD') : null,
        endDate: values.endDate ? values.endDate.format('YYYY-MM-DD') : null,
        streetAddress: values.streetAddress,
        city: values.city,
        state: values.state,
        zipCode: values.zipCode,
        location: values.location || values.city,
        // For backward compatibility with existing backend
        employeeName: `${values.firstName} ${values.lastName}`,
        address: `${values.streetAddress || ''}, ${values.city || ''}, ${values.state || ''} ${values.zipCode || ''}`.trim(),
        status: 'Active',
        createdBy: 'admin' // Replace with actual user from auth state
      };

      const response = await axios.post('/api/employee-department-master', payload);
      const employeeData = response.data?.responseData;

      if (employeeData) {
        // ✅ Show success modal with employee details
        setCreatedEmployee(employeeData);
        setSuccessModalVisible(true);
        form.resetFields();
      }
    } catch (error) {
      message.error(error.response?.data?.message || 'Failed to register employee');
    } finally {
      setLoading(false);
    }
  };

  const handleClear = () => {
    form.resetFields();
  };

  const handleCloseModal = () => {
    setSuccessModalVisible(false);
    setCreatedEmployee(null);
  };

  return (
    <div style={{ padding: '24px' }}>
      <Card
        title={
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <UserOutlined style={{ fontSize: '20px', color: '#1890ff' }} />
            <span>Employee Registration</span>
          </div>
        }
        bordered={false}
      >
        <Form form={form} layout="vertical" onFinish={handleSubmit}>
          {/* Personal Information Section */}
          <div style={{ marginBottom: '24px' }}>
            <h3 style={{ fontSize: '16px', fontWeight: 600, marginBottom: '16px', color: '#1890ff' }}>
              Personal Information
            </h3>
            <Row gutter={16}>
              <Col xs={24} sm={12} lg={8}>
                <Form.Item
                  label="Employee ID"
                  name="employeeId"
                  // ❌ NO required validation - auto-generated by backend
                  help="Auto-generated by system"
                >
                  <Input
                    placeholder="Auto-generated"
                    disabled={true}  // ✅ Always disabled - cannot be edited
                  />
                </Form.Item>
              </Col>
              <Col xs={24} sm={12} lg={8}>
                <Form.Item
                  label="First Name"
                  name="firstName"
                  rules={[{ required: true, message: 'Please enter first name' }]}
                >
                  <Input placeholder="Enter first name" />
                </Form.Item>
              </Col>
              <Col xs={24} sm={12} lg={8}>
                <Form.Item
                  label="Last Name"
                  name="lastName"
                  rules={[{ required: true, message: 'Please enter last name' }]}
                >
                  <Input placeholder="Enter last name" />
                </Form.Item>
              </Col>
              <Col xs={24} sm={12} lg={8}>
                <Form.Item
                  label="Email"
                  name="emailAddress"
                  rules={[
                    { required: true, message: 'Please enter email' },
                    { type: 'email', message: 'Please enter valid email' }
                  ]}
                >
                  <Input placeholder="Enter email address" />
                </Form.Item>
              </Col>
              <Col xs={24} sm={12} lg={8}>
                <Form.Item
                  label="Phone Number"
                  name="phoneNumber"
                  rules={[
                    { required: true, message: 'Please enter phone number' },
                    { pattern: /^\d{10}$/, message: 'Please enter 10-digit phone number' }
                  ]}
                >
                  <Input placeholder="Enter phone number" maxLength={10} />
                </Form.Item>
              </Col>
              <Col xs={24} sm={12} lg={8}>
                <Form.Item
                  label="Date of Birth"
                  name="dateOfBirth"
                  rules={[{ required: true, message: 'Please select date of birth' }]}
                >
                  <DatePicker
                    style={{ width: '100%' }}
                    format="DD-MM-YYYY"
                    disabledDate={(current) => current && current > dayjs().endOf('day')}
                  />
                </Form.Item>
              </Col>
            </Row>
          </div>

          <Divider />

          {/* Employment Information Section */}
          <div style={{ marginBottom: '24px' }}>
            <h3 style={{ fontSize: '16px', fontWeight: 600, marginBottom: '16px', color: '#1890ff' }}>
              Employment Information
            </h3>
            <Row gutter={16}>
              <Col xs={24} sm={12} lg={8}>
                <Form.Item
                  label="Department"
                  name="departmentName"
                  rules={[{ required: true, message: 'Please select department' }]}
                  tooltip="Department values are managed from LOV Management"
                >
                  <Select placeholder="Select department" loading={loadingDepartments} showSearch>
                    {departmentLOV.map((dept) => (
                      <Option key={dept.lovId} value={dept.lovValue}>
                        {dept.lovDisplayValue}
                      </Option>
                    ))}
                  </Select>
                </Form.Item>
              </Col>
              <Col xs={24} sm={12} lg={8}>
                <Form.Item
                  label="Designation"
                  name="designation"
                  rules={[{ required: true, message: 'Please select designation' }]}
                  tooltip="Designation values are managed from LOV Management"
                >
                  <Select placeholder="Select designation" loading={loadingDesignations} showSearch>
                    {designationLOV.map((desig) => (
                      <Option key={desig.lovId} value={desig.lovValue}>
                        {desig.lovDisplayValue}
                      </Option>
                    ))}
                  </Select>
                </Form.Item>
              </Col>
              <Col xs={24} sm={12} lg={8}>
                <Form.Item
                  label="Job Title"
                  name="jobTitle"
                >
                  <Input placeholder="Enter job title" />
                </Form.Item>
              </Col>
              <Col xs={24} sm={12} lg={8}>
                <Form.Item
                  label="Employment Type"
                  name="employmentType"
                >
                  <Input placeholder="Enter employment type (Full-time, Part-time, etc.)" />
                </Form.Item>
              </Col>
              <Col xs={24} sm={12} lg={8}>
                <Form.Item label="Manager" name="manager">
                  <Input placeholder="Enter manager name" />
                </Form.Item>
              </Col>
              <Col xs={24} sm={12} lg={8}>
                <Form.Item
                  label="Hire Date"
                  name="hireDate"
                  rules={[{ required: true, message: 'Please select hire date' }]}
                >
                  <DatePicker style={{ width: '100%' }} format="DD-MM-YYYY" />
                </Form.Item>
              </Col>
              <Col xs={24} sm={12} lg={8}>
                <Form.Item label="End Date (Optional)" name="endDate">
                  <DatePicker style={{ width: '100%' }} format="DD-MM-YYYY" />
                </Form.Item>
              </Col>
              <Col xs={24} sm={12} lg={8}>
                <Form.Item label="Annual Salary" name="annualSalary">
                  <Input type="number" placeholder="Enter annual salary" min={0} />
                </Form.Item>
              </Col>
            </Row>
          </div>

          <Divider />

          {/* Address Information Section */}
          <div style={{ marginBottom: '24px' }}>
            <h3 style={{ fontSize: '16px', fontWeight: 600, marginBottom: '16px', color: '#1890ff' }}>
              Address Information
            </h3>
            <Row gutter={16}>
              <Col xs={24}>
                <Form.Item label="Street Address" name="streetAddress">
                  <Input placeholder="Enter street address" />
                </Form.Item>
              </Col>
              <Col xs={24} sm={12} lg={8}>
                <Form.Item label="City" name="city">
                  <Input placeholder="Enter city" />
                </Form.Item>
              </Col>
              <Col xs={24} sm={12} lg={8}>
                <Form.Item label="State" name="state">
                  <Input placeholder="Enter state" />
                </Form.Item>
              </Col>
              <Col xs={24} sm={12} lg={8}>
                <Form.Item label="ZIP Code" name="zipCode">
                  <Input placeholder="Enter ZIP code" />
                </Form.Item>
              </Col>
              <Col xs={24} sm={12} lg={8}>
                <Form.Item label="Location" name="location">
                  <Select placeholder="Select office location" loading={loadingLocations} showSearch>
                    {locationLOV.map((loc) => (
                      <Option key={loc.lovId} value={loc.lovValue}>
                        {loc.lovDisplayValue}
                      </Option>
                    ))}
                  </Select>
                </Form.Item>
              </Col>
            </Row>
          </div>

          {/* Action Buttons */}
          <Form.Item style={{ marginTop: '32px', marginBottom: 0 }}>
            <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '12px' }}>
              <Button size="large" onClick={handleClear}>
                Clear Form
              </Button>
              <Button type="primary" size="large" htmlType="submit" loading={loading}>
                Register Employee
              </Button>
            </div>
          </Form.Item>
        </Form>
      </Card>

      {/* Success Modal */}
      <Modal
        title={
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <CheckCircleOutlined style={{ fontSize: '24px', color: '#52c41a' }} />
            <span>Employee Created Successfully!</span>
          </div>
        }
        open={successModalVisible}
        onCancel={handleCloseModal}
        footer={[
          <Button key="close" type="primary" onClick={handleCloseModal}>
            Close
          </Button>
        ]}
        width={700}
      >
        {createdEmployee && (
          <>
            {/* Employee ID Highlighted */}
            <div style={{
              backgroundColor: '#e6f7ff',
              padding: '16px',
              borderRadius: '8px',
              border: '2px solid #1890ff',
              marginBottom: '20px'
            }}>
              <div style={{ fontSize: '12px', color: '#1890ff', marginBottom: '4px' }}>
                Employee ID (Auto-Generated)
              </div>
              <div style={{ fontSize: '24px', fontWeight: 'bold', color: '#1890ff' }}>
                {createdEmployee.employeeId}
              </div>
            </div>

            <Divider />

            {/* Personal Information */}
            <h4 style={{ marginBottom: '12px', color: '#1890ff' }}>Personal Information</h4>
            <Descriptions bordered column={2} size="small">
              <Descriptions.Item label="Full Name">{createdEmployee.employeeName}</Descriptions.Item>
              <Descriptions.Item label="Email Address">{createdEmployee.emailAddress}</Descriptions.Item>
              <Descriptions.Item label="Phone Number">{createdEmployee.phoneNumber}</Descriptions.Item>
              <Descriptions.Item label="Status">
                <Tag color={createdEmployee.status === 'Active' ? 'green' : 'red'}>
                  {createdEmployee.status}
                </Tag>
              </Descriptions.Item>
            </Descriptions>

            <Divider />

            {/* Employment Information */}
            <h4 style={{ marginBottom: '12px', color: '#1890ff' }}>Employment Information</h4>
            <Descriptions bordered column={2} size="small">
              <Descriptions.Item label="Department">{createdEmployee.departmentName}</Descriptions.Item>
              <Descriptions.Item label="Designation">{createdEmployee.designation}</Descriptions.Item>
              <Descriptions.Item label="Location">{createdEmployee.location}</Descriptions.Item>
              <Descriptions.Item label="Address" span={2}>
                {createdEmployee.address}
              </Descriptions.Item>
            </Descriptions>

            <Divider />

            {/* System Information */}
            <h4 style={{ marginBottom: '12px', color: '#1890ff' }}>System Information</h4>
            <Descriptions bordered column={2} size="small">
              <Descriptions.Item label="Created By">{createdEmployee.createdBy}</Descriptions.Item>
              <Descriptions.Item label="Created Date">
                {dayjs(createdEmployee.createdDate).format('DD-MM-YYYY HH:mm:ss')}
              </Descriptions.Item>
            </Descriptions>
          </>
        )}
      </Modal>
    </div>
  );
};

export default EmployeeRegistration;
