import React from "react";
import FormInputItem from "./DKG_FormInputItem";
import CustomDatePicker from "./DKG_CustomTimePicker";

const DesignationContainer = ({
  formType,
  genByVisible,
  genDateValue,
  handleChange,
  issueVisible,
  issueDateValue,
  approvedVisible,
  approvedDateValue,
  processType,
  readOnly

}) => 
  {
  return (
    <div className="grid grid-cols-1 gap-4 md:grid-cols-3 md:gap-x-8 print-css-desg">
      {genByVisible && (
        <div className="each-desg flex-1">
          <h4> Generated By </h4>
          <FormInputItem
            placeholder="Name and Designation"
            name="genName"
            readOnly
          />
          <CustomDatePicker
            name="genDate"
            onChange={handleChange}
            defaultValue={genDateValue}
            readOnly={readOnly}
          />
        </div>
      )}

      {approvedVisible && (
        <div className="each-desg">
          <h4>

            {
              formType === "RN" ? "Returned / Submitted By" : "Approved By"
            }
          </h4>
          <FormInputItem
            placeholder="Name and Signature"
            name="approvedName"
            onChange={handleChange}
            readOnly={readOnly}
          />

          <CustomDatePicker
            defaultValue={approvedDateValue}
            name="approvedDate"
            onChange={handleChange}
            readOnly={readOnly}
          />
        </div>
      )}

      {issueVisible && (
        <div className="each-desg">
          <h4>
            {processType === "IRP" ||
            processType === "NIRP" ||
            processType === "IOP"
              ? "Received By"
              : "Verified By"}{" "}
          </h4>
          <FormInputItem
            placeholder="Name and Signature"
            name="issueName"
            onChange={handleChange}
            readOnly={readOnly}
          />

          <CustomDatePicker
            name="issueDate"
            onChange={handleChange}
            defaultValue={issueDateValue}
            readOnly={readOnly}
          />
        </div>
      )}
    </div>
  );
};

export default DesignationContainer;
